default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: bighash
  password: bighash
  pool: 5

development:
  <<: *default
  database: bighash_development

test:
  <<: *default
  database: bighash_test
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

production:
  <<: *default
  database: bighash_production
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
